vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Find [B]uffer" })
vim.keymap.set("n", "<leader>fc", "<cmd>Telescope command_history<cr>", { desc = "Find [C]ommand" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find [F]ile" })
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Find using [G]rep" })
vim.keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<cr>", { desc = "Find [H]elp" })
vim.keymap.set("n", "<leader>fw", "<cmd>Telescope grep_string<cr>", { desc = "Find current [W]ord" })
vim.keymap.set("n", "<leader>pp", require("pair_programming").pair, { desc = "[P]air programming" })
vim.keymap.set("n", "<leader>ps", require("pair_programming").solo, { desc = "[S]olo programming" })
vim.keymap.set("n", "<leader>pt", require("pair_programming").tty, { desc = "[T]eletypewriter" })
vim.keymap.set("n", "g-", ":bd<CR>", { desc = "Close current buffer" })
vim.keymap.set("n", "g0", ":b#<CR>", { desc = "Go to alternate buffer (last used)" })
vim.keymap.set("n", "g1", ":lua require('harpoon.ui').nav_file(1)<CR>", { desc = "Go to Harpoon file 1" })
vim.keymap.set("n", "g2", ":lua require('harpoon.ui').nav_file(2)<CR>", { desc = "Go to Harpoon file 2" })
vim.keymap.set("n", "g3", ":lua require('harpoon.ui').nav_file(3)<CR>", { desc = "Go to Harpoon file 3" })
vim.keymap.set("n", "g4", ":lua require('harpoon.ui').nav_file(4)<CR>", { desc = "Go to Harpoon file 4" })
vim.keymap.set("n", "g5", ":lua require('harpoon.ui').nav_file(5)<CR>", { desc = "Go to Harpoon file 5" })
vim.keymap.set("n", "ga", ":lua require('harpoon.mark').add_file()<CR>", { desc = "[A]dd file to Harpoon" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "gm", ":lua require('harpoon.ui').toggle_quick_menu()<CR>", { desc = "Toggle Harpoon [M]enu" })
vim.keymap.set("n", "gt", ":bnext<CR>", { silent = true, desc = "Go to next buffer" })
vim.keymap.set("n", "gT", ":bprevious<CR>", { silent = true, desc = "Go to previous buffer" })
vim.keymap.set("n", "L", vim.diagnostic.open_float, { desc = "Show diagnostic message" })
vim.keymap.set("v", "p", '"_dP', { desc = "Leave the pasted string in the registry" })
