vim.keymap.set("n", "<leader>b#", ":b#<CR>", { desc = "Go to alternate buffer (last used)" })
vim.keymap.set("n", "<leader>bd", ":bd<CR>", { desc = "[D]elete (close) current buffer" })
vim.keymap.set("n", "<leader>bn", ":bnext<CR>", { desc = "Go to [N]ext buffer" })
vim.keymap.set("n", "<leader>bp", ":bprevious<CR>", { desc = "Go to [P]revious buffer" })
vim.keymap.set("n", "<leader>d", vim.diagnostic.open_float, { desc = "Show [D]iagnostic message" })
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Find [B]uffer" })
vim.keymap.set("n", "<leader>fc", "<cmd>Telescope command_history<cr>", { desc = "Find [C]ommand" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find [F]ile" })
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Find using [G]rep" })
vim.keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<cr>", { desc = "Find [H]elp" })
vim.keymap.set("n", "<leader>fw", "<cmd>Telescope grep_string<cr>", { desc = "Find current [W]ord" })
vim.keymap.set("n", "<leader>pp", require("pair_programming").pair, { desc = "[P]air programming" })
vim.keymap.set("n", "<leader>ps", require("pair_programming").solo, { desc = "[S]olo programming" })
vim.keymap.set("n", "<leader>pt", require("pair_programming").tty, { desc = "[T]eletypewriter" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "gt", ":bnext<CR>", { silent = true, desc = "Go to next buffer" })
vim.keymap.set("n", "gT", ":bprevious<CR>", { silent = true, desc = "Go to previous buffer" })
vim.keymap.set("v", "p", '"_dP', { desc = "Leave the pasted string in the registry" })
