require("keymaps")
require("nvim")
require("plugins")
vim.cmd("source ~/.config/nvim/vim/vimrc.vim")
vim.cmd("source ~/.config/nvim/vim/gruvbox.vim")
vim.cmd("source ~/.config/nvim/vim/lightline-bufferline.vim")
vim.cmd("source ~/.config/nvim/vim/nvim-cmp.vim")
vim.cmd("source ~/.config/nvim/vim/telescope.vim")
