require("options")
require("keymaps")
require("plugins")
require("lsp")
vim.cmd("source ~/.config/nvim/vim/vimrc.vim")
vim.cmd("source ~/.config/nvim/vim/gruvbox.vim")
vim.cmd("source ~/.config/nvim/vim/lightline-bufferline.vim")
vim.cmd("source ~/.config/nvim/vim/telescope.vim")
